Capturing user login and user register as events
HDRUK/gateway-api pull request #206
Opened 2020-11-13 09:18 UTC by RichardHobbsPA

2020-11-13 10:08 UTC, RobinKavPA commented on src/resources/eventlog/eventlog.controller.js
> +        });
General approach looks ok but I recommend a couple of things.

1. You don't need to pass in 'req' and 'res', these are the default parameters passed into our controllers given by Express when an endpoint/route is hit.  In your case you can just pass the user object.

2. You could actually make this function a single line given you are assembling the object in the correct form in each of the calling instances.

e.g. 

`logEvent: async (user, event) => await EventLogModel.create({...event});`

2020-11-16 10:34 UTC, PaulMcCaffertyPA requested changes

2020-11-16 10:34 UTC, PaulMcCaffertyPA commented on src/resources/user/user.register.route.js
> +        email: email,
We shouldn't be recording the users emails in a log event, same with the provider ID, it will not be any use to us. And instead of saving the provider we can add that as part of the event i.e. event = user_login_google

2020-11-16 14:18 UTC, RichardHobbsPA commented on src/resources/user/user.register.route.js
> +        email: email,
Done!

2020-11-17 15:15 UTC, PaulMcCaffertyPA approved these changes

2020-11-20 10:31 UTC, RobinKavPA approved these changes

2020-11-20 13:51 UTC, merged