Implementing logic to search for datasets by pid
HDRUK/gateway-api pull request #208
Opened 2020-11-18 11:30 UTC by RichardHobbsPA

2020-11-18 11:40 UTC, PaulMcCaffertyPA requested changes

2020-11-18 11:40 UTC, PaulMcCaffertyPA commented on src/resources/dataset/dataset.route.js
> +        { $match: { $and: [{ pid: req.params.datasetID }, {activeflag: 'active'}] } }
Small change - Change the req.params.datasetID to datasetId here

2020-11-18 11:40 UTC, PaulMcCaffertyPA commented on src/resources/dataset/dataset.route.js
> +            { $match: { $and: [{ datasetid: req.params.datasetID }] } }
Small change - Change the req.params.datasetID to datasetId here

2020-11-18 11:40 UTC, PaulMcCaffertyPA commented on src/resources/dataset/dataset.route.js
> +    if (data.length === 0) data[0] = await loadDataset(datasetId)
Move this line `if (data.length === 0) data[0] = await loadDataset(datasetId)` to after line 70, this line of code is used to pull a version from the MDC if it doesn't exist on our DB

2020-11-18 15:18 UTC, PaulMcCaffertyPA submitted a review, later dismissed

2020-11-20 10:30 UTC, RobinKavPA commented on src/resources/dataset/dataset.route.js
> +    }
Richard, I can suggest a number of improvements here and for your awareness.

1. Should line 62 be saying /:datasetPID ?  Otherwise it seems confusing that in some circumstances below, we are overwriting the request parameter to be 'data[0].datasetid'.  I'm assuming we are now sending a 'pid' into this endpoint?

2. We should test that 'datasetId' / 'dataset'PID' is provided and is valid, we can do this on line 64 by destructuring from the req.params and returning a 400 bad request if datasetId is empty e.g.

`let { datasetId = ''} = req.params;
  if(_.isEmpty(datasetId) { return res.status(400).json({ success: false });`

3. On line 68 you are using an aggregate function to query Mongo which will always return you an array even if you are expecting a single object back.  This is why you are using data[0] and having to check the length is greater than 0 before accessing data. e.g. on line 72.

If you change that to 'findOne' and pass in the datasetId and activeflag in the same way, you will only ever get one result returned as an object.  That object could be named 'dataset' for example as below.

`let dataset = await Data.findOne({ pid: datasetId, activeflag: 'active'});
if(!_.nil(dataset)){
        // Set the actual datasetId value based on pid provided
        datasetId = dataset.datasetid;
    }`

The same can be appplied to line 78 - 85;
You would then need to update you references of data[0] to dataset.

2020-11-20 10:30 UTC, RobinKavPA commented on src/resources/dataset/dataset.route.js
> +    ]);
4. 'let p' and 'x' doesn't make it clear on what the variables are referring to

5. This could be changed as above because you aren't actually aggregating anything.
`let relatedData = await Data.find({ "relatedObjects": { $elemMatch: { "objectId": datasetId } } })`

then you could map over the relatedData and make the changes in line 100 before returning the data

2020-11-23 14:50 UTC, PaulMcCaffertyPA approved these changes

2020-11-23 15:45 UTC, RichardHobbsPA commented on src/resources/dataset/dataset.route.js
> +    }
Robin, the parameter can be either PID or a datasetId which is why I left it as datasetID.  It gets overwritten with a datasetID only if we are passing in a PID.  I've made changes for all the other suggestions you provided.

2020-11-23 15:46 UTC, RichardHobbsPA commented on src/resources/dataset/dataset.route.js
> +    ]);
See comment above.  Completely agree with point no 4.  Some of these issues were already there before I touched this but definitely good to implement best practices on all the code we touch if we have time.  Cheers for providing code examples btw!

2020-11-23 16:23 UTC, RobinKavPA approved these changes
Looks much better, nicer and easier to read in my opinion.  Good stuff!

2020-11-23 19:16 UTC, merged