Minimised team datasets: Add gwdmVersion, and fix format of response.
HDRUK/gateway-api pull request #996
Opened 2024-12-18 17:15 UTC by spco

## Screenshots (if relevant)

## Describe your changes
BE fix for this bug returned data inside an array (this took me _far_ too long to spot!), so that's fixed.

Also adds `gwdmVersion` to the returned payload because FE needs that to decide on how to render publisher name.

## Issue ticket link
https://hdruk.atlassian.net/browse/GAT-5786

## Environment / Configuration changes (if applicable)

## Requires migrations being run?

## If not using the pre-push hook. Confirm tests pass:

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added appropriate unit tests
- [ ] I have created mocks for unit tests (where appropriate)
- [ ] I have added appropriate Behat tests to confirm AC (if applicable)
- [ ] I have added Swagger annotations for new endpoints (if applicable)
- [ ] I have added audit logs for new operation logic (if applicable)
- [ ] I have added new environment variables to the .env.example file (if applicable)
- [ ] I have added new environment variables to terraform repository (if applicable)

2024-12-18 17:27 UTC, spco commented on app/Http/Traits/TrimPayload.php
> +        $miniMetadata['gwdmVersion'] = $input['gwdmVersion'];
@loki-sinclair-hdruk is this a fix in the wrong place? Feels a bit wrong to put this into this function, but I can't hoist this into the calling function so easily, because then I end up trying to modify a `Dataset` directly, and I get yelled at.

2024-12-19 04:03 UTC, loki-sinclair-hdruk commented on app/Http/Traits/TrimPayload.php
> +        $miniMetadata['gwdmVersion'] = $input['gwdmVersion'];
I'm sure this is fine, at least for now. We do have to manipulate metadata in transit, in several places. I don't see this being any different tbh.

2024-12-19 04:03 UTC, loki-sinclair-hdruk approved these changes

2024-12-19 11:57 UTC, calmacx requested changes

2024-12-19 11:57 UTC, calmacx commented on app/Http/Controllers/Api/V1/TeamController.php
> +                $datasets
This doesnt seem right. Should be like:
```
return response()->json([
         'message' => Config::get('statuscodes.STATUS_OK.message'),
          'data' => $datasets,
 ], Config::get('statuscodes.STATUS_OK.code'));
```

Assuming this endpoint is used by the FE, the `useGet` hook in the frontend is expecting that data be returned as `{message:<>, data:<>}`:
```
const json = await response.json();
if (!withPagination) return json.data;
const { data, current_page, last_page, next_page_url, ...rest } =    json;
```

2024-12-19 12:47 UTC, spco commented on app/Http/Controllers/Api/V1/TeamController.php
> +                $datasets
All of our `index` endpoints don't use that form, they use this form instead. (I have no idea why that is the case!)

The response has the structure 
```
current_page, data, first_page_url etc
```
exactly as `useGet` wants, so it all works out fine with the FE, no message required.

2024-12-19 12:51 UTC, spco commented on app/Http/Controllers/Api/V1/TeamController.php
> +                $datasets
(I'm guessing we don't need the outer `'data'` key because the response from the paginate function already handles all of that)

2024-12-19 13:51 UTC, calmacx commented on app/Http/Controllers/Api/V1/TeamController.php
> +                $datasets
Got you! Thanks!

2024-12-19 13:51 UTC, calmacx approved these changes

2024-12-19 13:54 UTC, merged